### ISSUE TITLE
chunks causes the server to lag.

### ISSUE THREAD

**Issue by XiaoYeYa** [senseiwells/ServerReplay#25]
When I enter `/replay start chunks around -2 1 radius 50 in minecraft:overworld named`, my server experiences lag for a while and then recovers. However, using `/replay start players `works fine, so it's quite strange. I also tried switching to the new "Fabric Language Kotlin" but it didn't help. There are no errors in my console, just a warning about server thread response timeout.

![%7B9B242D44-86AE-433c-904F-CC640A915154%7D](https://github.com/senseiwells/ServerReplay/assets/124911800/7e7ec630-4d0c-4d0e-aa2b-41bedeee3821)

![%7B3C218A1D-31A6-468e-8108-5F337CE70A59%7D](https://github.com/senseiwells/ServerReplay/assets/124911800/2417270f-53cf-47d1-b7c9-d3c37357d553)

**Comment by senseiwells** [comment]
That is because if you set the radius to 50 you are recording a **101x101 chunk area**. That's a **HUGE** area the server has to process. For context, a player,on view distance 16, is 33x33 (it's actually less than this but for simplicity).

So when recording a player 33x33 the server will have to initially process 1,089 chunks.

When recording a chunk 101x101 the server will have to initially process 10,201. That's almost 10x the amount of chunks.

**Comment by senseiwells** [comment]
Perhaps the chunks could be initialised over time on the server, but recording such a large area is unrealistic anyways as it will result in such large replay files that replay mod will struggle viewing them.

This will not be fixed anytime soon.
