### ISSUE TITLE
Large chunk recording crashes the server

### ISSUE THREAD

**Issue by HoldYourWaffle** [senseiwells/ServerReplay#66]
I'd love to have a recording of all of the inhabited world, but unfortunately this ambition causes the server to crash on startup :(

Logs:
- [latest.log](https://github.com/user-attachments/files/17130037/latest.log)
- [crash-2024-09-25_13.12.02-server.txt](https://github.com/user-attachments/files/17130040/crash-2024-09-25_13.12.02-server.txt)

Configuration:
```json
"chunks": [
	{
		"name": "...",
		"dimension": "minecraft:overworld",
		"from_x": -189,
		"from_z": -70,
		"to_x": 37,
		"to_z": 15
	}
  ]
```

**Comment by senseiwells** [comment]
This is because the chunk recorder is trying to load all the chunks all at once to record them, you can set the initial chunk recording radius in the config with `"chunk_recorder_load_radius"`, this will only load a few chunks on startup and only record them as and when they're loaded. See the README for more information
