### ISSUE TITLE
Freeze after /replay status command

### ISSUE THREAD

**Issue by ItzSkyReed** [senseiwells/ServerReplay#7]
I started the replay in chunks -5 5 4 -5, after 2 hours I entered the command /replay status and the server froze for 40 seconds, the players have been kicked.
Just after recording started, however, the /replay status command worked instantly and correctly.
There are no errors in server log. just this line
`[21:33:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 40321ms or 806 ticks behind`

I also think I must say that during this a large tnt duper was working inside these chunks, perhaps this is the problem, but the server was not lagging because of this dupers, the mspt was about 30-35

If you need any other info I can help you

**Comment by senseiwells** [comment]
Yeah this would be because the mod is trying to calculate the compressed replay to display to you.
There's no real good way of calculating a compressed size unless you compress it, so essentially it's just compressing the replay when you run the status command.

In the version below I've made it do it asynchronously (so it won't make the server lag), but it still may take a while for the status to be displayed to the player. I have also added a config to completely disable reporting the compressed size in the status if you do not care for it.

Try [this version](https://filebin.net/ihae9dqhv6noz3no/ServerReplay-1.0.4_mc1.20.4.jar) and let me know if there are still any issues.

**Comment by ItzSkyReed** [comment]
Thanks, will test today

**Comment by ItzSkyReed** [comment]
![image](https://github.com/senseiwells/ServerReplay/assets/93844414/acaaebc5-7a0b-4eca-acc4-8fc827258bab)
looks like compressed size is in bytes, not megabytes

**Comment by ItzSkyReed** [comment]
Thanks
